### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by xyzwps** [ant-design/antd-migration-helper#2]
When I run command `antd-migration-helper`, an exception threw:

```
$ antd-migration-helper
/usr/local/lib/node_modules/antd-migration-helper/rules/input-type-textarea.js:11
        if (attribute.name.name === 'type' && attribute.value.value === 'textarea') {
                          ^

TypeError: Cannot read property 'name' of undefined
    at Object.JSXOpeningElement (/usr/local/lib/node_modules/antd-migration-helper/rules/input-type-textarea.js:11:27)
    at traversersList.(anonymous function).push (/usr/local/lib/node_modules/antd-migration-helper/lib/check-for-deprecations.js:32:54)
    at traversersList.(anonymous function).forEach.fn (/usr/local/lib/node_modules/antd-migration-helper/lib/check-for-deprecations.js:48:46)
    at Array.forEach (native)
    at traverser.(anonymous function) (/usr/local/lib/node_modules/antd-migration-helper/lib/check-for-deprecations.js:48:32)
    at NodePath._call (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babel-traverse/lib/index.js:114:17)
```

**Comment by Madridspark** [comment]
I also received it.

**Comment by bradjabel** [comment]
+1 

Was running on node 8.7.0

**Comment by yesmeck** [comment]
Try antd-migration-helper@0.2.1

**Comment by xyzwps** [comment]
Thanks!

**Comment by Madridspark** [comment]
Thanks but sorry.
Cuz I got another error:

use `antd-migration-helper@0.3.0`

```
\antd-migration-helper\node_modules\babylon\lib\index.js:4457
  throw err;
  ^

SyntaxError: Unexpected token (8:50)
    at Parser.pp$5.raise (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseExprAtom (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:3627:50)
    at Parser.parseExprAtom (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:3344:19)
    at Parser.parseMaybeAssign (C:\Users\madri\AppData\Roaming\npm\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:6474:20)
```

**Comment by yesmeck** [comment]
@Madridspark Could you upgrade `antd-migration-helper` to `0.3.1` and run it using `DEBUG=antd-migration-helper antd-migration-helper` to see it stops on which file? And can you post your file content? Do you use any syntax which not in ES6?

**Comment by Madridspark** [comment]
It sames as the tool scanned my `assets` directory. 
There is a file names `iconfont.js`........

I'm sorry. It's not your tool's fault. So sorry..
