### ISSUE TITLE
throw err @0.3.1

### ISSUE THREAD

**Issue by tomgao365** [ant-design/antd-migration-helper#3]
```
1. Use `Table[onRow]` instead
  Line 814: src/DmpConfig/screens/AppConfig/screens/GroupManage/screens/Type/List.jsx
  Reason: `Table[onRowClick|onRowDoubleClick|onRowContextMenu|onRowMouseEnter|onRowMouseLeave]` have been deprecated
  More info: https://ant.design/changelog#3.0.0

2. Use `Card[hoverable]` instead
  Line 164: src/DmpConfig/screens/AppConfig/screens/PageManage/Configure/Basic.jsx
  Reason: `Card[noHovering]` has been renamed to `Card[hoverable]`
  More info: https://ant.design/changelog#3.0.0

3. Use `Table[onRow]` instead
  Line 818: src/DmpConfig/screens/CommonConfig/screens/CommonTypeManage/screens/List.jsx
  Reason: `Table[onRowClick|onRowDoubleClick|onRowContextMenu|onRowMouseEnter|onRowMouseLeave]` have been deprecated
  More info: https://ant.design/changelog#3.0.0
D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:4457
  throw err;
  ^

SyntaxError: Unexpected token, expected ( (40:0)
    at Parser.pp$5.raise (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp.expect (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:1749:33)
    at Parser.pp$1.parseFunctionParams (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:2394:8)
    at Parser.parseFunctionParams (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:6376:13)
    at Parser.pp$1.parseFunction (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:2385:8)
    at Parser.pp$1.parseFunctionStatement (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:2053:15)
    at Parser.pp$1.parseStatement (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:1839:19)
    at Parser.parseStatement (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:5910:22)
    at Parser.pp$1.parseExportDeclaration (D:\Server\nodejs\node_global\node_modules\antd-migration-helper\node_modules\babylon\lib\index.js:2666:15)
```

**Comment by yesmeck** [comment]
Could you provide more info ? https://github.com/ant-design/antd-migration-helper/issues/2#issuecomment-352629382

**Comment by tomgao365** [comment]
@yesmeck 
Sorry :joy: ,
That is my mistake. My colleague's code actually has a syntax error!

**Comment by tomgao365** [comment]
@yesmeck 
Sorry, emoj
That is our mistake. My colleague's code actually has a syntax error.
