### ISSUE TITLE
SyntaxError: Unexpected token (34:47)

### ISSUE THREAD

**Issue by Ginhing** [ant-design/antd-migration-helper#6]
Thanks for your great job!

There is a exception when I input a file which has the "import()" statement. Here is the error stacks:

/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:4457
  throw err;
  ^

SyntaxError: Unexpected token (34:47)
    at Parser.pp$5.raise (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:3627:50)
    at Parser.parseExprAtom (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/usr/local/lib/node_modules/antd-migration-helper/node_modules/babylon/lib/index.js:6474:20)

**Comment by yesmeck** [comment]
antd-migration-helper@0.3.2
